/* osrs/protocol.h - OSRS network protocol definitions
 * AUTO-GENERATED from rsprot source. Do not edit manually.
 * Revision: OSRS 239
 */

#ifndef OSRS_PROTOCOL_H
#define OSRS_PROTOCOL_H

#include "osrs/isaac.h"
#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define OSRS_REVISION 239
#define OSRS_GAME_PORT 43594

#define OSRS_PKT_VAR_BYTE -1
#define OSRS_PKT_VAR_SHORT -2

/* IN packet opcodes */
enum {
  OSRS_IN_MIDI_SONG_STOP = 0,
  OSRS_IN_CAM_TARGET_V3 = 1,
  OSRS_IN_NPC_INFO_LARGE_V5 = 2,
  OSRS_IN_CAM_RESET = 3,
  OSRS_IN_NPC_HEADICON_SPECIFIC = 4,
  OSRS_IN_CHAT_FILTER_SETTINGS_PRIVATECHAT = 5,
  OSRS_IN_SET_PLAYER_OP = 6,
  OSRS_IN_IF_OPENSUB = 7,
  OSRS_IN_REFLECTION_CHECKER = 8,
  OSRS_IN_UPDATE_ZONE_PARTIAL_FOLLOWS = 9,
  OSRS_IN_LOC_DEL = 10,
  OSRS_IN_VARCLAN = 11,
  OSRS_IN_VARP_LARGE = 12,
  OSRS_IN_OBJ_COUNT_SPECIFIC = 13,
  OSRS_IN_IF_SETROTATESPEED = 14,
  OSRS_IN_MESSAGE_PRIVATE_ECHO = 15,
  OSRS_IN_IF_SETPLAYERMODEL_BASECOLOUR = 16,
  OSRS_IN_IF_SETANGLE = 17,
  OSRS_IN_UPDATE_INV_PARTIAL = 18,
  OSRS_IN_MESSAGE_PRIVATE = 19,
  OSRS_IN_NPC_ANIM_SPECIFIC = 20,
  OSRS_IN_HIDELOCOPS = 21,
  OSRS_IN_UPDATE_INV_FULL = 22,
  OSRS_IN_IF_CLOSESUB = 23,
  OSRS_IN_UNKNOWN_STRING = 24,
  OSRS_IN_IF_RESYNC_V2 = 25,
  OSRS_IN_SET_HEATMAP_ENABLED = 26,
  OSRS_IN_UPDATE_FRIENDCHAT_CHANNEL_FULL_V2 = 27,
  OSRS_IN_PLAYER_INFO = 28,
  OSRS_IN_CAM_SMOOTHRESET = 29,
  OSRS_IN_LOC_ANIM_SPECIFIC = 30,
  OSRS_IN_UPDATE_RUNWEIGHT = 31,
  OSRS_IN_SOUND_AREA = 32,
  OSRS_IN_LOC_ADD_CHANGE_V2 = 33,
  OSRS_IN_LOC_MERGE = 34,
  OSRS_IN_MIDI_SONG_V2 = 35,
  OSRS_IN_FRIENDLIST_LOADED = 36,
  OSRS_IN_UPDATE_REBOOT_TIMER_V2 = 37,
  OSRS_IN_CAM_MODE = 38,
  OSRS_IN_URL_OPEN = 39,
  OSRS_IN_CAM_ROTATETO = 40,
  OSRS_IN_OBJ_DEL_SPECIFIC = 41,
  OSRS_IN_UPDATE_IGNORELIST = 42,
  OSRS_IN_MINIMAP_TOGGLE = 43,
  OSRS_IN_VARP_RESET = 44,
  OSRS_IN_UPDATE_INV_STOPTRANSMIT = 45,
  OSRS_IN_UPDATE_STAT_V2 = 46,
  OSRS_IN_SET_ACTIVE_WORLD_V2 = 47,
  OSRS_IN_PROJANIM_SPECIFIC_V4 = 48,
  OSRS_IN_REBUILD_NORMAL_V2 = 49,
  OSRS_IN_HINT_ARROW = 50,
  OSRS_IN_CAM_ROTATEBY = 51,
  OSRS_IN_OBJ_CUSTOMISE_SPECIFIC = 52,
  OSRS_IN_UPDATE_STOCKMARKET_SLOT = 53,
  OSRS_IN_UPDATE_ZONE_FULL_FOLLOWS = 54,
  OSRS_IN_IF_SETCOLOUR = 55,
  OSRS_IN_UPDATE_TRADINGPOST = 56,
  OSRS_IN_LOGOUT = 57,
  OSRS_IN_LOGOUT_WITHREASON = 58,
  OSRS_IN_IF_SETANIM = 59,
  OSRS_IN_VARCLAN_DISABLE = 60,
  OSRS_IN_MESSAGE_FRIENDCHANNEL = 61,
  OSRS_IN_MESSAGE_CLANCHANNEL_SYSTEM = 62,
  OSRS_IN_IF_SETHIDE = 63,
  OSRS_IN_UPDATE_RUNENERGY = 64,
  OSRS_IN_OCULUS_SYNC = 65,
  OSRS_IN_RESET_INTERACTION_MODE = 66,
  OSRS_IN_SITE_SETTINGS = 67,
  OSRS_IN_ACCOUNT_FLAGS = 68,
  OSRS_IN_CLANCHANNEL_FULL = 69,
  OSRS_IN_OBJ_ENABLED_OPS_SPECIFIC = 70,
  OSRS_IN_CLANSETTINGS_DELTA = 71,
  OSRS_IN_PLAYER_SPOTANIM_SPECIFIC = 72,
  OSRS_IN_HIDEOBJOPS = 73,
  OSRS_IN_MESSAGE_GAME = 74,
  OSRS_IN_HIDENPCOPS = 75,
  OSRS_IN_VARP_SYNC = 76,
  OSRS_IN_SYNTH_SOUND = 77,
  OSRS_IN_OBJ_ADD_SPECIFIC = 78,
  OSRS_IN_SET_INTERACTION_MODE = 79,
  OSRS_IN_IF_SETTEXT = 80,
  OSRS_IN_CLANSETTINGS_FULL = 81,
  OSRS_IN_IF_SETSCROLLPOS = 82,
  OSRS_IN_SERVER_TICK_END = 83,
  OSRS_IN_IF_SETNPCHEAD = 84,
  OSRS_IN_NPC_INFO_SMALL_V5 = 85,
  OSRS_IN_MAP_ANIM = 86,
  OSRS_IN_CAM_TARGET_V4 = 87,
  OSRS_IN_VARCLAN_ENABLE = 88,
  OSRS_IN_IF_SETNPCHEAD_ACTIVE = 89,
  OSRS_IN_MAP_ANIM_SPECIFIC = 90,
  OSRS_IN_LOGOUT_TRANSFER = 91,
  OSRS_IN_RESET_ANIMS = 92,
  OSRS_IN_PACKET_GROUP_START = 93,
  OSRS_IN_IF_CLEARINV = 94,
  OSRS_IN_CLANCHANNEL_DELTA = 95,
  OSRS_IN_IF_OPENTOP = 96,
  OSRS_IN_VARP_SMALL = 97,
  OSRS_IN_IF_SETPLAYERMODEL_OBJ = 98,
  OSRS_IN_MIDI_SONG_WITHSECONDARY = 99,
  OSRS_IN_IF_SETPLAYERMODEL_BODYTYPE = 100,
  OSRS_IN_NPC_SPOTANIM_SPECIFIC = 101,
  OSRS_IN_IF_SETPOSITION = 102,
  OSRS_IN_CAM_SHAKE = 103,
  OSRS_IN_OBJ_UNCUSTOMISE_SPECIFIC = 104,
  OSRS_IN_UPDATE_ZONE_PARTIAL_ENCLOSED = 105,
  OSRS_IN_IF_SETOBJECT = 106,
  OSRS_IN_MIDI_SWAP = 107,
  OSRS_IN_IF_SETEVENTS_V2 = 108,
  OSRS_IN_REBUILD_WORLDENTITY_V4 = 109,
  OSRS_IN_LOC_ANIM = 110,
  OSRS_IN_UPDATE_FRIENDLIST = 111,
  OSRS_IN_UPDATE_FRIENDCHAT_CHANNEL_SINGLEUSER = 112,
  OSRS_IN_UPDATE_UID192 = 113,
  OSRS_IN_RUNCLIENTSCRIPT = 114,
  OSRS_IN_SEND_PING = 115,
  OSRS_IN_SET_NPC_UPDATE_ORIGIN = 116,
  OSRS_IN_TRIGGER_ONDIALOGABORT = 117,
  OSRS_IN_MIDI_JINGLE = 118,
  OSRS_IN_ANIM_SPECIFIC = 119,
  OSRS_IN_IF_SETPLAYERHEAD = 120,
  OSRS_IN_IF_SETPLAYERMODEL_SELF = 121,
  OSRS_IN_WORLDENTITY_INFO_V7 = 122,
  OSRS_IN_IF_MOVESUB = 123,
  OSRS_IN_CHAT_FILTER_SETTINGS = 124,
  OSRS_IN_REBUILD_REGION_V2 = 125,
  OSRS_IN_HISCORE_REPLY = 126,
  OSRS_IN_MESSAGE_CLANCHANNEL = 127,
  OSRS_IN_CAM_MOVETO_ARC_V3 = 128,
  OSRS_IN_CAM_MOVETO_ARC_V2 = 129,
  OSRS_IN_CAM_MOVETO_CYCLES_V3 = 130,
  OSRS_IN_CAM_UNLOCK = 131,
  OSRS_IN_GROUP_FULL = 132,
  OSRS_IN_GROUP_VAR_LONG = 133,
  OSRS_IN_CAM_MOVETO_CYCLES_V2 = 134,
  OSRS_IN_CAM_SKYBOX = 135,
  OSRS_IN_GROUP_VAR = 136,
  OSRS_IN_CAM_LOOKAT_CYCLES = 137,
  OSRS_IN_AMBIENTSOUND_STOP = 138,
  OSRS_IN_CAM_LOOKAT_V2 = 139,
  OSRS_IN_GROUP_VAR_INT = 140,
  OSRS_IN_CAM_ROTATETO_COORDINATE_V2 = 141,
  OSRS_IN_IF_SETMODEL_V2 = 142,
  OSRS_IN_SET_MAP_FLAG_V2 = 143,
  OSRS_IN_CAM_LOOKAT_V3 = 144,
  OSRS_IN_AMBIENTSOUND_START = 145,
  OSRS_IN_CAM_MOVETO_V2 = 146,
  OSRS_IN_CAM_MOVETO_V3 = 147,
  OSRS_IN_CAM_ROTATETO_COORDINATE_V3 = 148,
};

/* OUT packet opcodes */
enum {
  OSRS_OUT_OPNPC6 = 0,
  OSRS_OUT_SEND_PING_REPLY = 1,
  OSRS_OUT_CLANSETTINGS_FULL_REQUEST = 2,
  OSRS_OUT_OPPLAYER2 = 3,
  OSRS_OUT_IDLE = 4,
  OSRS_OUT_EXIT_FREECAM = 5,
  OSRS_OUT_EVENT_NATIVE_MOUSE_MOVE = 6,
  OSRS_OUT_OPOBJ3_V2 = 7,
  OSRS_OUT_EVENT_CAMERA_POSITION = 8,
  OSRS_OUT_IGNORELIST_DEL = 9,
  OSRS_OUT_WINDOW_STATUS = 10,
  OSRS_OUT_REFLECTION_CHECK_REPLY = 12,
  OSRS_OUT_OPNPC2_V2 = 13,
  OSRS_OUT_OPWORLDENTITY1 = 14,
  OSRS_OUT_OPLOC4_V2 = 15,
  OSRS_OUT_EVENT_MOUSE_SCROLL = 16,
  OSRS_OUT_HISCORE_REQUEST = 17,
  OSRS_OUT_OPNPC3_V2 = 19,
  OSRS_OUT_FRIENDCHAT_JOIN_LEAVE = 20,
  OSRS_OUT_OPPLAYER7 = 22,
  OSRS_OUT_OPNPCU = 23,
  OSRS_OUT_MAP_BUILD_COMPLETE = 24,
  OSRS_OUT_RESUME_P_NAMEDIALOG = 26,
  OSRS_OUT_IF_BUTTONT = 27,
  OSRS_OUT_FRIENDLIST_ADD = 28,
  OSRS_OUT_EVENT_APPLET_FOCUS = 29,
  OSRS_OUT_OPOBJ4_V2 = 31,
  OSRS_OUT_RESUME_P_OBJDIALOG = 32,
  OSRS_OUT_DETECT_MODIFIED_CLIENT = 33,
  OSRS_OUT_CLIENT_CHEAT = 34,
  OSRS_OUT_EVENT_MOUSE_CLICK_V2 = 35,
  OSRS_OUT_OPPLAYER4 = 37,
  OSRS_OUT_CLANCHANNEL_KICKUSER = 38,
  OSRS_OUT_SOUND_JINGLEEND = 39,
  OSRS_OUT_IF_SUBOP = 40,
  OSRS_OUT_OPOBJ5_V2 = 43,
  OSRS_OUT_SET_HEADING = 44,
  OSRS_OUT_OPNPC4_V2 = 45,
  OSRS_OUT_OPOBJ1_V2 = 46,
  OSRS_OUT_IF_BUTTONX = 47,
  OSRS_OUT_IF_BUTTOND = 48,
  OSRS_OUT_TELEPORT = 50,
  OSRS_OUT_IF_BUTTON = 51,
  OSRS_OUT_OPLOCU = 52,
  OSRS_OUT_OPPLAYER8 = 53,
  OSRS_OUT_EVENT_KEYBOARD = 54,
  OSRS_OUT_FRIENDCHAT_SETRANK = 55,
  OSRS_OUT_IF_SCRIPT_TRIGGER = 56,
  OSRS_OUT_OPPLAYER5 = 57,
  OSRS_OUT_OPOBJ6 = 58,
  OSRS_OUT_SET_CHATFILTERSETTINGS = 59,
  OSRS_OUT_SEND_SNAPSHOT = 60,
  OSRS_OUT_MEMBERSHIP_PROMOTION_ELIGIBILITY = 61,
  OSRS_OUT_OPLOCT = 62,
  OSRS_OUT_RESUME_P_COUNTDIALOG_LONG = 63,
  OSRS_OUT_RESUME_P_STRINGDIALOG = 64,
  OSRS_OUT_FRIENDLIST_DEL = 65,
  OSRS_OUT_EVENT_MOUSE_CLICK_V1 = 66,
  OSRS_OUT_MOVE_MINIMAPCLICK = 67,
  OSRS_OUT_MESSAGE_PUBLIC = 69,
  OSRS_OUT_OPPLAYER6 = 70,
  OSRS_OUT_OPWORLDENTITYT = 72,
  OSRS_OUT_OPLOC1_V2 = 73,
  OSRS_OUT_OPOBJ2_V2 = 74,
  OSRS_OUT_RESUME_P_COUNTDIALOG = 75,
  OSRS_OUT_OPOBJT = 76,
  OSRS_OUT_UPDATE_PLAYER_MODEL_V2 = 77,
  OSRS_OUT_OPLOC6 = 78,
  OSRS_OUT_OPPLAYERT = 79,
  OSRS_OUT_OPWORLDENTITY2 = 80,
  OSRS_OUT_IGNORELIST_ADD = 82,
  OSRS_OUT_OPWORLDENTITY4 = 83,
  OSRS_OUT_OPNPC5_V2 = 85,
  OSRS_OUT_OPNPCT = 86,
  OSRS_OUT_OPPLAYERU = 87,
  OSRS_OUT_NO_TIMEOUT = 89,
  OSRS_OUT_OPWORLDENTITYU = 90,
  OSRS_OUT_IF_CRMVIEW_OP = 91,
  OSRS_OUT_OPPLAYER3 = 92,
  OSRS_OUT_OPPLAYER1 = 93,
  OSRS_OUT_CLOSE_MODAL = 95,
  OSRS_OUT_AFFINEDCLANSETTINGS_SETMUTED_FROMCHANNEL = 96,
  OSRS_OUT_CONNECTION_TELEMETRY = 97,
  OSRS_OUT_OPWORLDENTITY6 = 98,
  OSRS_OUT_CLICKWORLDMAP = 99,
  OSRS_OUT_OPWORLDENTITY3 = 100,
  OSRS_OUT_FRIENDCHAT_KICK = 101,
  OSRS_OUT_OPNPC1_V2 = 102,
  OSRS_OUT_OPLOC2_V2 = 103,
  OSRS_OUT_OPLOC3_V2 = 104,
  OSRS_OUT_RSEVEN_STATUS = 105,
  OSRS_OUT_OPWORLDENTITY5 = 106,
  OSRS_OUT_BUG_REPORT = 108,
  OSRS_OUT_EVENT_MOUSE_MOVE = 110,
  OSRS_OUT_MESSAGE_PRIVATE = 111,
  OSRS_OUT_CLANCHANNEL_FULL_REQUEST = 112,
  OSRS_OUT_OPOBJU = 113,
  OSRS_OUT_MOVE_GAMECLICK = 114,
  OSRS_OUT_RESUME_PAUSEBUTTON = 115,
  OSRS_OUT_OPLOC5_V2 = 116,
};

/* Login response codes */
#define OSRS_LOGINRESP_OK 2
#define OSRS_LOGINRESP_INVALID_CRED 3
#define OSRS_LOGINRESP_BANNED 4
#define OSRS_LOGINRESP_DUPLICATE 5
#define OSRS_LOGINRESP_OUT_OF_DATE 6
#define OSRS_LOGINRESP_SERVER_FULL 7
#define OSRS_LOGINRESP_LOGINSERVER_OFFLINE 8
#define OSRS_LOGINRESP_IP_LIMIT 9
#define OSRS_LOGINRESP_BAD_SESSION_ID 10
#define OSRS_LOGINRESP_FORCE_PASSWORD_CHANGE 11
#define OSRS_LOGINRESP_NEED_MEMBERS 12
#define OSRS_LOGINRESP_TOO_MANY_ATTEMPTS 16
#define OSRS_LOGINRESP_IN_MEMBERS_AREA 17
#define OSRS_LOGINRESP_LOCKED 18
#define OSRS_LOGINRESP_HOP_BLOCKED 21
#define OSRS_LOGINRESP_INVALID_LOGIN_PACKET 22
#define OSRS_LOGINRESP_AUTHENTICATOR 56
#define OSRS_LOGINRESP_PROOF_OF_WORK 69

/* Packet read/write */
typedef struct {
  uint8_t data[5000];
  size_t len;
  size_t pos;
} osrs_packet_t;

typedef enum {
  OSRS_CONN_IDLE,
  OSRS_CONN_HANDSHAKE,
  OSRS_CONN_INIT_SENT,
  OSRS_CONN_LOGIN_SENT,
  OSRS_CONN_POW,
  OSRS_CONN_GAME,
  OSRS_CONN_DISCONNECTED
} osrs_conn_state_t;

typedef struct {
  osrs_conn_state_t state;
  osrs_isaac_t isaac_in;
  osrs_isaac_t isaac_out;
  int player_index;
  bool members;
  int staff_mod_level;
  bool player_mod;
  uint64_t account_hash;
  uint64_t user_id;
  uint64_t user_hash;
  bool resizable;
  int width;
  int height;

  /* Login fields */
  char username[65];
  char secret[128];
  int auth_type;
  uint32_t index_crcs[23];
  uint32_t xtea_seed[4];
  uint64_t session_id;

  /* Proof-of-work challenge */
  int pow_version;
  int pow_difficulty;
  char pow_salt[1200];
} osrs_protocol_t;

void osrs_protocol_init(osrs_protocol_t *proto);
void osrs_protocol_set_game_keys(osrs_protocol_t *proto,
                                 const uint32_t keys[4]);
int osrs_game_read_packet(osrs_protocol_t *proto, const uint8_t *data,
                          size_t len, osrs_packet_t *packet, size_t *consumed);
int osrs_game_write_packet(osrs_protocol_t *proto, int opcode,
                           const uint8_t *payload, size_t payload_len,
                           uint8_t *out, size_t out_len);

/* Outgoing packet builders */
size_t osrs_build_move_gameclick(osrs_packet_t *p, int x, int z, bool run);
size_t osrs_build_window_status(osrs_packet_t *p, int mode, int w, int h);
size_t osrs_build_event_applet_focus(osrs_packet_t *p, bool focused);

/* Size tables (extern) */
extern const int8_t osrs_server_packet_sizes[256];
extern const int8_t osrs_client_packet_sizes[256];

const char *osrs_server_packet_name(int opcode);
const char *osrs_client_packet_name(int opcode);

/* Login handshake */
size_t osrs_login_build_init(uint8_t *out);
int osrs_login_process_init_response(osrs_protocol_t *proto,
                                     const uint8_t *data, size_t len,
                                     size_t *consumed);
size_t osrs_login_build_gamelogin(osrs_protocol_t *proto, uint8_t *out);
int osrs_login_parse_response(osrs_protocol_t *proto, const uint8_t *data,
                              size_t len, size_t *consumed);
size_t osrs_login_build_pow_reply(uint64_t result, uint8_t *out);

#ifdef __cplusplus
}
#endif

#endif /* OSRS_PROTOCOL_H */
